processo_uab/urls.py
from django.conf.urls import url
from django.contrib import admin

from .views import inicio_page
from inscricoes.views import (
    inscricao_page,
    minha_inscricao,
    comprovante_inscricao,
    codigo_barras,
    socio_economico_inscricao,
)
from contas.views import (
    login_page,
    logout_page,
    meus_dados,
    recursos,
    recurso_inscricao,
    recurso_resultado,
)
from cursos.views import (
    get_cursos,
    get_curso,
)


urlpatterns = [
    url(r'^$', inicio_page, name='inicio'),
    url(r'^login/$', login_page, name='login'),
    url(r'^logout/$', logout_page, name='logout'),
    url(r'^candidato/dados/$', meus_dados, name='meus_dados'),
    url(r'^candidato/inscricao/$', minha_inscricao, name='minha_inscricao'),
    url(r'^candidato/comprovante/$', comprovante_inscricao, name='comprovante_inscricao'),
    url(r'^candidato/socioeconomico/$', socio_economico_inscricao, name='socio_economico_inscricao'),
    url(r'^candidato/recursos/$', recursos, name='recursos'),
    url(r'^candidato/recursos/(?P<tipo>\w+)$', recurso_inscricao, name='recurso_inscricao'),
    url(r'^candidato/recursos/(?P<tipo>\w+)/resultado$', recurso_resultado, name='recurso_resultado'),
    url(r'^inscricao/$', inscricao_page, name='inscricao'),
    url(r'^inscricao/get_cursos/(?P<id>\d+)$', get_cursos, name='cursos'),
    url(r'^inscricao/get_curso/(?P<id>\d+)$', get_curso, name='curso'),
    url(r'^inscricao/codigo_barras/(?P<text>\w+)$', codigo_barras, name='codigo_barras'),
    url(r'^admin/', admin.site.urls),
]

cidades/models.py
from django.db import models

from cursos.models import Curso

class Cidade(models.Model):
    cidade = models.CharField(max_length=120)
    curso  = models.ManyToManyField(Curso)

    def __str__(self):
        return self.cidade

inscricoes/models.py
from django.db import models
from django.db.models.signals import post_save

from cidades.models import Cidade
from cursos.models import Curso
from contas.models import Usuario

from .choices import (
    MODALIDADE_CHOICES,
    INSCRICAO_CHOICES,
    RECURSO_CHOICES,
    TIPO_RECURSO,
)


class Inscricao(models.Model):
    candidato = models.OneToOneField(Usuario)
    cidade_curso = models.ForeignKey(Cidade, related_name='cidade_curso')
    curso = models.ForeignKey(Curso)
    local_prova = models.ForeignKey(Cidade, related_name='local_prova')
    necessidade_esp = models.CharField(max_length=120, blank=True, null=True)
    modalidade = models.CharField(max_length=10, choices=MODALIDADE_CHOICES)
    reserva = models.CharField(max_length=2, editable=False, choices=INSCRICAO_CHOICES, null=True, blank=True)
    socio_economico = models.CharField(max_length=2, editable=False, choices=INSCRICAO_CHOICES, null=True, blank=True)
    valor = models.CharField(max_length=6, default='100,00')
    timestamp = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return "{} {}".format(self.candidato.perfil.nome, self.candidato.perfil.sobrenome)


def post_save_reserva_receiver(sender, created, instance, *args, **kwargs):
    if created and instance.modalidade != 'universal':
        instance.reserva = '1'  # Inscrito
        instance.save()


post_save.connect(post_save_reserva_receiver, sender=Inscricao)


class SocioEconomico(models.Model):
    inscricao = models.OneToOneField(Inscricao)
    pai = models.CharField(max_length=120, null=True)
    mae = models.CharField(max_length=120, null=True)
    questao1 = models.CharField(max_length=10, null=True)
    questao2 = models.CharField(max_length=10, null=True)
    questao3 = models.CharField(max_length=10, null=True)
    questao4 = models.CharField(max_length=10, null=True)
    questao5 = models.CharField(max_length=10, null=True)
    questao6 = models.CharField(max_length=10, null=True)
    questao7 = models.CharField(max_length=10, null=True)
    questao8 = models.CharField(max_length=10, null=True)
    questao9 = models.CharField(max_length=10, null=True)
    questao10 = models.CharField(max_length=10, null=True)
    questao11 = models.CharField(max_length=10, null=True)
    questao12 = models.CharField(max_length=10, null=True)
    timestamp = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return "{} {}".format(self.inscricao.candidato.perfil.nome, self.inscricao.candidato.perfil.sobrenome)


def post_save_socio_economico_receiver(sender, created, instance, *args, **kwargs):
    if created:
        inscricao_socio = instance.inscricao
        inscricao_socio.socio_economico = '1'  # Inscrito
        inscricao_socio.save()


post_save.connect(post_save_socio_economico_receiver, sender=SocioEconomico)


class Recurso(models.Model):
    inscricao = models.ForeignKey(Inscricao)
    status = models.CharField(max_length=120, choices=RECURSO_CHOICES)
    motivo_indeferimento = models.TextField()
    recurso = models.TextField(blank=True, null=True)
    resposta_recurso = models.TextField(blank=True, null=True)
    tipo = models.CharField(max_length=120, choices=TIPO_RECURSO)
    timestamp = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return "{} {}".format(self.inscricao.candidato.perfil.nome, self.inscricao.candidato.perfil.sobrenome)

enderecos/forms.py
from django import forms

from .models import Endereco

class EnderecoForm(forms.ModelForm):
    cep = forms.CharField(label='CEP', widget=forms.TextInput(attrs={'class': 'form-control text cep', 'placeholder': 'CEP'}))
    rua = forms.CharField(label='Rua', widget=forms.TextInput(attrs={'class': 'form-control text', 'placeholder': 'Rua'}))
    numero = forms.CharField(label='Número', widget=forms.TextInput(attrs={'class': 'form-control text', 'placeholder': 'Número'}))
    complemento = forms.CharField(required=False, label='Complemento', widget=forms.TextInput(
        attrs={'class': 'form-control text', 'placeholder': 'Complemento'}))
    bairro = forms.CharField(label='Bairro', widget=forms.TextInput(attrs={'class': 'form-control text', 'placeholder': 'Bairro'}))
    cidade = forms.CharField(label='Cidade', widget=forms.TextInput(attrs={'class': 'form-control text', 'placeholder': 'Cidade'}))
    estado = forms.CharField(label='Estado', widget=forms.TextInput(attrs={'class': 'form-control text', 'placeholder': 'Estado'}))

    class Meta:
        model = Endereco
        fields = '__all__'

inscricoes/views.py
from django.contrib.auth import login
from django.http import request
from django.shortcuts import render
from django.shortcuts import redirect
from django.http import HttpResponse

from .utils import criar_codigo_barras

from .forms import (
    InscricaoForm,
    MinhaInscricaoForm,
    SocioEconomicoForm,
)
from enderecos.forms import EnderecoForm
from contas.forms import (
    PerfilForm,
    UsuarioForm
)

from .models import Inscricao


def inscricao_page(request):
    if request.user.is_authenticated():
        return redirect('inicio')
    endereco = EnderecoForm(request.POST or None)
    perfil = PerfilForm(request.POST or None)
    inscricao = InscricaoForm(request.POST or None)
    usuario = UsuarioForm(request.POST or None)
    if request.method == 'POST':
        if endereco.is_valid() and perfil.is_valid() and inscricao.is_valid() and usuario.is_valid():
            endereco_obj = endereco.save()
            perfil_obj = perfil.save()
            usuario_obj = usuario.save(commit=False)
            usuario_obj.endereco = endereco_obj
            usuario_obj.perfil = perfil_obj
            usuario_obj.nome = perfil_obj.nome
            usuario_obj.save()
            inscricao_obj = inscricao.save(commit=False)
            inscricao_obj.candidato = usuario_obj
            inscricao_obj.save()
            login(request, usuario_obj)
            return redirect('login')
    context = {
        'titulo': 'Inscrição - ',
        'form_endereco': endereco,
        'form_usuario': usuario,
        'form_perfil': perfil,
        'form_inscricao': inscricao,
    }
    return render(request, 'inscricoes/inscricao.html', context)


def minha_inscricao(request):
    usuario = request.user
    inscricao = Inscricao.objects.get(candidato__exact=usuario.id)
    if inscricao:
        inscricao_form = MinhaInscricaoForm(request.POST or None, instance=inscricao)
    context = {
        'form_inscricao': inscricao_form,
    }
    return render(request, 'inscricoes/minha_inscricao.html', context)


def comprovante_inscricao(request):
    usuario = request.user
    inscricao = Inscricao.objects.get(candidato__exact=usuario.id)
    context = {
        'inscricao': inscricao,
    }
    return render(request, 'inscricoes/comprovante.html', context)


def codigo_barras(request, text):
    codigo_barra = criar_codigo_barras(text)
    binaryStuff = codigo_barra.asString('gif')
    return HttpResponse(binaryStuff, 'image/gif')


def socio_economico_inscricao(request):
    if request.user.inscricao.socio_economico != None:
        return redirect('inicio')
    socio = SocioEconomicoForm(request.POST or None)
    if socio.is_valid():
        socio_obj = socio.save(commit=False)
        socio_obj.inscricao = request.user.inscricao
        socio_obj.save()
        return redirect('inicio')
    context = {
        'socio_form': socio,
    }
    return render(request, 'inscricoes/socio_inscricao.html', context)

inscricoes/templates/inscricoes/comprovante.html
<!doctype html>
<html lang="en">
    <head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
        <title>Comprovante Inscrição - Processo Seletivo Universidade Aberta do Brasil (UAB)</title>
        <style>
            body {
                width: 595px;
            }
        </style>
    </head>
    <body>
        <div class="content">
            <div class="navbar">
                <img src="{% url 'codigo_barras' text=inscricao.id %}" alt="Codigo de Barras valor {{ inscricao.id }}">
                <img src="{% url 'codigo_barras' text=inscricao.id %}" alt="Codigo de Barras valor {{ inscricao.id }}">
            </div>
            <div>
                <h1 class="text-center display-7">Processo Seletivo - UAB</h1>
                <h3 class="text-center">Comprovante de Inscrição</h3>
            </div>

            <div class="row">
                <div class="col-md-2"></div>
                <div>
                    <p>Nome completo: {{ request.user.nome }} {{ request.user.perfil.sobrenome }}<br/>
                    RG: {{ request.user.perfil.rg }}<br/>
                    CPF: {{ request.user.perfil.cpf }}<br/>
                    Endereço: {{ request.user.endereco.rua }}{% if request.user.endereco.numero %},  {{ request.user.endereco.numero }}{% endif %}{% if request.user.endereco.numero %},  {{ request.user.endereco.bairro }}{% endif %}<br/>
                    Cidade:  {{ request.user.endereco.cidade }}<br/>
                    Curso Selecionado: {{ inscricao.curso.curso }}<br/>
                    Cidade do Curso: {{ inscricao.cidade_curso.cidade }}<br/>
                    Local da prova: {{ inscricao.local_prova.cidade }}</p>
                </div>
            </div>
            <div class="navbar">
                <img src="{% url 'codigo_barras' text=inscricao.id %}" alt="Codigo de Barras valor {{ inscricao.id }}">
                <img src="{% url 'codigo_barras' text=inscricao.id %}" alt="Codigo de Barras valor {{ inscricao.id }}">
            </div>
        </div>
        <!-- Optional JavaScript -->
        <!-- jQuery first, then Popper.js, then Bootstrap JS -->
        <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/rasterizehtml/1.3.0/rasterizeHTML.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jspdf/1.3.5/jspdf.debug.js" integrity="sha384-CchuzHs077vGtfhGYl9Qtc7Vx64rXBXdIAZIPbItbNyWIRTdG0oYAqki3Ry13Yzu" crossorigin="anonymous"></script>
        <script>
            /**
             * html2pdf.js
             * Copyright (c) 2014 Steven Spungin (TwelveTone LLC)  steven@twelvetone.tv
             *
             * Licensed under the MIT License.
             * http://opensource.org/licenses/mit-license
             */

            function html2pdf (html,pdf,callback) {
                var canvas = pdf.canvas;
                if (!canvas) {
                    alert('jsPDF canvas plugin not installed');
                    return;
                }
                canvas.pdf = pdf;
                pdf.annotations = {

                    _nameMap : [],

                    createAnnotation : function(href,bounds) {
                        var x = pdf.context2d._wrapX(bounds.left);
                        var y = pdf.context2d._wrapY(bounds.top);
                        var page = pdf.context2d._page(bounds.top);
                        var options;
                        var index = href.indexOf('#');
                        if (index >= 0) {
                            options = {
                                name : href.substring(index + 1)
                            };
                        } else {
                            options = {
                                url : href
                            };
                        }
                        pdf.link(x, y, bounds.right - bounds.left, bounds.bottom - bounds.top, options);
                    },

                    setName : function(name,bounds) {
                        var x = pdf.context2d._wrapX(bounds.left);
                        var y = pdf.context2d._wrapY(bounds.top);
                        var page = pdf.context2d._page(bounds.top);
                        this._nameMap[name] = {
                            page : page,
                            x : x,
                            y : y
                        };
                    }

                };
                canvas.annotations = pdf.annotations;

                pdf.context2d._pageBreakAt = function(y) {
                    this.pageBreaks.push(y);
                };

                pdf.context2d._gotoPage = function(pageOneBased) {
                    while (pdf.internal.getNumberOfPages() < pageOneBased) {
                        pdf.addPage();
                    }
                    pdf.setPage(pageOneBased);
                }

                if (typeof html === 'string') {
                    // remove all scripts
                    html = html.replace(/<script\b[^<]*(?:(?!<\/script>)<[^<]*)*<\/script>/gi, '');

                    var iframe = document.createElement('iframe');
                    //iframe.style.width = canvas.width;
                    //iframe.src = "";
                    //iframe.document.domain =
                    document.body.appendChild(iframe);
                    var doc;
                    doc = iframe.contentDocument;
                    if (doc == undefined || doc == null) {
                        doc = iframe.contentWindow.document;
                    }
                    //iframe.setAttribute('style', 'position:absolute;right:0; top:0; bottom:0; height:100%; width:500px');

                    doc.open();
                    doc.write(html);
                    doc.close();

                    var promise = html2canvas(doc.body, {
                        canvas : canvas,
                        onrendered : function(canvas) {
                            if (callback) {
                                if (iframe) {
                                    iframe.parentElement.removeChild(iframe);
                                }
                                callback(pdf);
                            }
                        }
                    });

                } else {
                    var body = html;
                    var promise = html2canvas(body, {
                        canvas : canvas,
                        onrendered : function(canvas) {
                            if (callback) {
                                if (iframe) {
                                    iframe.parentElement.removeChild(iframe);
                                }
                                callback(pdf);
                            }
                        }
                    });
                }
            }
        </script>
        <script>
            $(document).ready(function(){
                var pdf = new jsPDF('p', 'pt', 'A4');
                html2pdf(document.body, pdf, function(pdf){
                    var iframe = document.createElement('iframe');
                    iframe.setAttribute('style','position:absolute;right:0; top:0; bottom:0; height:100%; width:100%');
                    document.body.appendChild(iframe);
                    $('.content').html('')
                    iframe.src = pdf.output('datauristring');
                });
            });
        </script>
    </body>
</html>

inscricoes/templates/inscricoes/inscricao.html
{% extends 'base.html' %}

{% load widget_tweaks %}

{% block content %}



<form method="POST">
    {% csrf_token %}
    <header>
        <h2>Informações Pessoais</h2>
        <hr/>
        <br/>
    </header>
    <div class="row">
        {% for perfil in form_perfil %}
            <div class="form-group
            {% if forloop.counter == 2 %}col-6 6u
            {% elif forloop.counter == 3 %}col-2 2u
            {% else %}col-4 4u{% endif %}">
                <label for="{{ perfil.name }}">
                    {{ perfil.label }}
                </label>
                {% if perfil.errors %}
                    {{ perfil|add_class:"is-invalid" }}
                    <div class="invalid-feedback">
                        {% for error in perfil.errors %}
                            {{ error }}
                        {% endfor %}
                    </div>
                {% else %}
                    {{  perfil|add_class:'mb' }}
                {% endif %}
            </div>
        {% endfor %}
        {% for usuario in form_usuario %}
            <div class="form-group col-4 4u">
                <label for="{{ usuario.name }}">
                    {{ usuario.label }}
                </label>
                {% if usuario.errors %}
                    {{ usuario|add_class:"is-invalid" }}
                    <div class="invalid-feedback">
                        {% for error in usuario.errors %}
                            {{ error }}
                        {% endfor %}
                    </div>
                {% else %}
                    {{  usuario|add_class:'mb' }}
                {% endif %}
            </div>
        {% endfor %}
    </div>
    <header>
        <h2>Endereço</h2>
        <hr/>
        <br/>
    </header>
    <div class="row">
        {% for endereco in form_endereco %}
            <div class="form-group
                {% if forloop.counter == 2 %}col-6 6u
                {% elif forloop.counter == 3 %}col-2 2u
                {% else %}col-4 4u{% endif %}">
                <label for="{{ endereco.name }}">
                    {{ endereco.label }}
                </label>
                {% if endereco.errors %}
                    {{ endereco|add_class:"is-invalid" }}
                    <div class="invalid-feedback">
                        {% for error in endereco.errors %}
                            {{ error }}
                        {% endfor %}
                    </div>
                {% else %}
                    {{  endereco|add_class:'mb' }}
                {% endif %}
            </div>
        {% endfor %}
    </div>
    <header>
        <h2>Inscrição</h2>
        <hr/>
        <br/>
    </header>
    <div class="row">
        {% for inscricao in form_inscricao %}
            {% if forloop.last %}
                {{  inscricao }}
            {% else %}
                <div class="form-group col-6 6u">
                    <label for="{{ inscricao.name }}">
                        {{ inscricao.label }}
                    </label>
                    {% if inscricao.errors %}
                        {{ inscricao|add_class:"is-invalid" }}
                        <div class="invalid-feedback">
                            {% for error in inscricao.errors %}
                                {{ error }}
                            {% endfor %}
                        </div>
                    {% else %}
                        {{  inscricao|add_class:'mb' }}
                    {% endif %}
                </div>
            {% endif %}
        {% endfor %}
    </div>
    <button type="submit" class="btn btn-primary button">Inscrever</button>
</form>
{% endblock %}


{% block js %}
    <!--Script Costumizado-->
    <script>
        $(document).ready(function(){
            $('#id_curso').html('<option>---------</option>')

            // Máscaras
            $('.cep').mask('00000-000');
            $('.cpf').mask('000.000.000-00', {reverse: true});
            $('.celular').mask('(00) 00000-0000');
            $('.data').mask("00/00/0000", {placeholder: "__/__/____"});

            // Busca CEP
            $("#id_cep").change(function(){
                $.ajax({
                    dataType: "json",
                    url: 'https://viacep.com.br/ws/' + $(this).val() + '/json/',
                    success: function(data){
                        $("#id_rua").val(data.logradouro);
                        $("#id_bairro").val(data.bairro);
                        $("#id_cidade").val(data.localidade);
                        $("#id_estado").val(data.uf);
                    }
                });
            });

            // Pegar csrftoken
            function getCookie(name) {
                var cookieValue = null;
                if (document.cookie && document.cookie !== '') {
                    var cookies = document.cookie.split(';');
                    for (var i = 0; i < cookies.length; i++) {
                        var cookie = jQuery.trim(cookies[i]);
                        // Does this cookie string begin with the name we want?
                        if (cookie.substring(0, name.length + 1) === (name + '=')) {
                            cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                            break;
                        }
                    }
                }
                return cookieValue;
            }
            var csrftoken = getCookie('csrftoken');

            // Altera Curso
            $("#id_cidade_curso").change(function(){
                $.ajax({
                    dataType: "json",
                    url: 'get_cursos/' + $(this).val(),
                    method: "POST",
                    data: {
                        csrfmiddlewaretoken: csrftoken
                    },
                    success: function(data){
                        var text = ''
                        var i;
                        for (i in data){
                            text = text + '<option value="' + data[i].id + '">' + data[i].curso + '</option>'
                        }
                        $('#id_curso').html(text)
                        $("#curso_hidden").val(data[0].id)
                    }
                });
            });

            $("#id_curso").change(function(){
                $("#curso_hidden").val($(this).val())
            });

            // Busca Curso Selecionado
            $("#curso_hidden").ready(function(){
                if ($("#curso_hidden").val() != ""){
                    $.ajax({
                        dataType: "json",
                        url: 'get_curso/' + $("#curso_hidden").val(),
                        method: "POST",
                        data: {
                            csrfmiddlewaretoken: csrftoken
                        },
                        success: function(data){
                            text = '<option value="' + data[0].id + '">' + data[0].curso + '</option>'
                            $('#id_curso').html(text)
                        }
                    });
                }
            });
        });
    </script>
{% endblock %}

inscricoes/templates/inscricoes/minha_inscricao.html
{% extends 'base.html' %}

{% load widget_tweaks %}

{% block content %}
<form method="POST">
    {% csrf_token %}
    <header>
        <h2>Minha Inscrição</h2>
        <hr/>
        <br/>
    </header>
    <div class="row">
        {% for inscricao in form_inscricao %}
            <div class="form-group col-6 6u">
                <label for="{{ inscricao.name }}">
                    {{ inscricao.label }}
                </label>
                {% if inscricao.errors %}
                    {{ inscricao|add_class:"is-invalid" }}
                    <div class="invalid-feedback" style="color:red;">
                        {% for error in inscricao.errors %}
                            {{ error }}
                        {% endfor %}
                    </div>
                {% else %}
                    {{  inscricao|add_class:'mb'|attr:"readonly" }}
                {% endif %}
            </div>
        {% endfor %}
    </div>
</form>
{% endblock %}

inscricoes/templates/inscricoes/socio_inscricao.html
{% extends 'base.html' %}

{% load widget_tweaks %}

{% block content %}
<form method="POST">
    {% csrf_token %}
    <header>
        <h2>Dados Pessoais</h2>
        <hr/>
        <br/>
    </header>
    <div class="row">
        {% for socio in socio_form %}
            {% if forloop.counter == 3 %}
                </div>
                <br/>
                <header>
                    <h2>Questionários de Avaliação</h2>
                    <hr/>
                    <br/>
                </header>
                <div class="row">
            {% endif %}
            <div class="form-group col-12 12u mb">
                <label for="{{ socio.name }}">
                    {{ socio.label }}
                </label>
                {% if forloop.counter > 2 %}
                    {% if socio.errors %}
                        {% for choice in socio %}
                            {{ choice }}
                            <!--<div class="col-12 12u">-->
                                <!--<div class="form-check">-->
                                    <!--{{ choice.tag }}-->
                                    <!--<label class="form-check-label" for="{{ choice.data.name }}">-->
                                        <!--{{ choice.data.label }}-->
                                    <!--</label>-->
                                <!--</div>-->
                            <!--</div>-->
                        {% endfor %}
                        <div class="alert alert-danger" role="alert">
                            <strong style="color:red;">
                                {% for error in socio.errors %}
                                    {{ error }}
                                {% endfor %}
                            </strong>
                        </div>
                    {% else %}
                        {% for choice in socio %}
                            {{ choice }}
                            <!--<div class="col-12 12u">-->
                                <!--<div class="form-check">-->
                                    <!--{{ choice.tag }}-->
                                    <!--<label class="form-check-label" for="{{ choice.data.name }}">-->
                                        <!--{{ choice.data.label }}-->
                                    <!--</label>-->
                                <!--</div>-->
                            <!--</div>-->
                        {% endfor %}
                    {% endif %}
                {% else %}
                    {% if socio.errors %}
                        {{ socio|add_class:"is-invalid" }}
                        <div class="invalid-feedback" style="color:red;">
                            {% for error in socio.errors %}
                                {{ error }}
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ socio }}
                    {% endif %}
                {% endif %}
            </div>
        {% endfor %}
    </div>
    <button type="submit" class="btn btn-primary button">Inscrever no Socioeconômico</button>
</form>
{% endblock %}